export const HomeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Browse Github',
    headline: 'Surf Github with the best tools',
    description:
      'Github Profile Finder is a non conmercial open source search engine for finding Github users and repositories built with Github Rest API and React.js',
    buttonLabel: 'View the Source',
    imgStart: false,
    img: require('../../images/svg-4.svg').default,
    link: 'https://simonsmith.github.io/github-user-search/#/search',
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
  };
export const HomeObjTwo = {
    id: 'signup',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Modern API',
    headline: 'Access the data of millions of accounts on Github',
    description:"Github APIs or Github ReST APIs are the APIs that you can use to interact with GitHub. They allow you to create and manage repositories, branches, issues, pull requests, and many more.",
    buttonLabel: 'Read API docs',
    imgStart: true,
    img: require('../../images/svg-2.svg').default,
    link: 'https://docs.github.com/en/free-pro-team@latest/rest',
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
  };